### ISSUE TITLE
Jumping up walls

### ISSUE THREAD

**Issue by Bejno** [Turnary-Games/Battery-Golem#1]
## The player can jump up walls... :disappointed:

![wallhump](https://cloud.githubusercontent.com/assets/12370172/9729783/3a653c48-5612-11e5-92e0-7b6e6841091c.gif)
:small_red_triangle: Add a limit to what counts as "grounded" so its not grounded when on a steep sloap

**Comment by applejag** [comment]
:small_blue_diamond: The script now calculates the angle of the touching collider and if that is < the slope limit: deny jumping.
